
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "About Us", name: "about", widget: "text" }
          - { label: "Services", name: "services", widget: "list" }
          - { label: "Contact Info", name: "contact", widget: "text" }
